In [1]:
import numpy as np
import openvds

In [2]:
filename = "../10_samples/10_samples_default.vds"

In [3]:
vds = openvds.open(filename, "")
layout = openvds.getLayout(vds)
grid_definition = layout.getVDSIJKGridDefinitionFromMetadata()

In [29]:
axis = {}
for i in range(layout.getDimensionality()):
    ax = {}
    ax["name"] = layout.getDimensionName(i)
    ax["nsamples"] = layout.getDimensionNumSamples(i)
    ax["min"] = layout.getDimensionMin(i)
    ax["max"] = layout.getDimensionMax(i)
    ax["stepsize"] = (ax["max"]-ax["min"])/ (ax["nsamples"]-1)
    axis[ax["name"]] = ax

In [30]:
axis

{'Sample': {'name': 'Sample',
  'nsamples': 10,
  'min': 4.0,
  'max': 40.0,
  'stepsize': 4.0},
 'Crossline': {'name': 'Crossline',
  'nsamples': 2,
  'min': 10.0,
  'max': 11.0,
  'stepsize': 1.0},
 'Inline': {'name': 'Inline',
  'nsamples': 3,
  'min': 1.0,
  'max': 5.0,
  'stepsize': 2.0}}

In [5]:
index_origin = np.array([0,0])

In [31]:
index_origin_as_CDP = np.array(grid_definition.origin)

In [37]:
annotated_to_cdp_inline_step = np.array(grid_definition.iUnitStep) / axis["Inline"]["stepsize"]
annotated_to_cdp_xline_step = np.array(grid_definition.jUnitStep) / axis["Crossline"]["stepsize"]

In [54]:
annotated_origin = index_origin_as_CDP - (axis["Inline"]["min"] * annotated_to_cdp_inline_step + 
                                          axis["Crossline"]["min"] * annotated_to_cdp_xline_step)

In [57]:
index_origin_in_cdp = annotated_origin + \
        (axis["Inline"]["min"] * annotated_to_cdp_inline_step +
         axis["Crossline"]["min"] * annotated_to_cdp_xline_step)

In [58]:
index_origin_in_cdp

array([ 2.,  0., -4.])

In [55]:
annotated_origin

array([ 19., -32.,  -4.])

In [43]:
axis["Inline"]["min"]* annotated_to_cdp_inline_step

array([3., 2., 0.])

In [46]:
axis["Crossline"]["min"] * annotated_to_cdp_xline_step

array([-20.,  30.,   0.])

In [41]:
annotated_origin

array([ 19., -32.,  -4.])

In [47]:
origin = np.array([-3, -12])

In [53]:
origin + 10*(annotated_to_cdp_inline_step[0:2])

array([27.,  8.])

In [36]:
annotated_to_cdp_inline_step

array([3., 2., 0.])

In [38]:
annotated_to_cdp_xline_step

array([-2.,  3.,  0.])

In [ ]:
layout.getDimensionName(0)

In [ ]:
axis = {}
for i in range(layout.getDimensionality()):
    ax = {}
    ax["name"] = layout.getDimensionName(i)
    ax["nsamples"] = layout.getDimensionNumSamples(i)
    ax["min"] = layout.getDimensionMin(i)
    ax["max"] = layout.getDimensionMax(i)
    axis[ax["name"]] = ax

In [ ]:
axis

In [13]:
grid_definition.iUnitStep

(6.0, 4.0, 0.0)

In [14]:
print("ChannelCount: {}".format(layout.getChannelCount()))
for i in range(layout.getChannelCount()):
    print("  Channel Name: {}".format(layout.getChannelName(i)))
    print("    Value range: {} - {}".format(layout.getChannelValueRangeMin(i), layout.getChannelValueRangeMax(i)))
    
print("Dimensionality: {}".format(layout.getDimensionality()))
for i in range(layout.getDimensionality()):
    print("  Dimension name: {}".format(layout.getDimensionName(i)))
    print("    Number of samples: {}".format(layout.getDimensionNumSamples(i)))
    print("    Coordinate min max {} - {}".format(layout.getDimensionMin(i), layout.getDimensionMax(i)))

ChannelCount: 3
  Channel Name: Amplitude
    Value range: -14.5 - 25.5
  Channel Name: Trace
    Value range: 0.0 - 1.0
  Channel Name: SEGYTraceHeader
    Value range: 0.0 - 255.0
Dimensionality: 3
  Dimension name: Sample
    Number of samples: 10
    Coordinate min max 4.0 - 40.0
  Dimension name: Crossline
    Number of samples: 2
    Coordinate min max 10.0 - 11.0
  Dimension name: Inline
    Number of samples: 3
    Coordinate min max 1.0 - 5.0


In [15]:
metadata = layout.getMetadata

In [16]:
metadata

<bound method PyCapsule.getMetadata of <openvds.core.VolumeDataLayout object at 0x1050a4cf0>>

In [17]:
res = layout.getVDSIJKGridDefinitionFromMetadata()

In [18]:
res.dimensionMap

(2, 1, 0)

In [19]:
res.iUnitStep

(6.0, 4.0, 0.0)

In [20]:
res.origin

(2.0, 0.0, -4.0)

In [21]:
res.iUnitStep

(6.0, 4.0, 0.0)

In [22]:
res.jUnitStep

(-2.0, 3.0, 0.0)

In [64]:
res.kUnitStep

(0.0, 0.0, -4.0)

In [65]:
off = layout.getChannelIntegerOffset(2)

In [66]:
off

0.0

In [67]:
meta = layout.getMetadata()

TypeError: getMetadata(): incompatible function arguments. The following argument types are supported:
    1. (self: openvds.core.MetadataReadAccess, key: openvds.core.MetadataKey) -> PyMetadataVariant
    2. (self: openvds.core.MetadataReadAccess, category: str, name: str, type: openvds.core.MetadataType) -> PyMetadataVariant

Invoked with: <openvds.core.VolumeDataLayout object at 0x1050a4cf0>

In [68]:
k = layout.metadataKeys

In [69]:
key_list = []
for v in k:
    key_list.append(v)

In [70]:
key_list[0]

MetadataKey(category='SurveyCoordinateSystem', name='CRSWkt', type=MetadataType.String)

In [71]:
type(key_list[0])

openvds.core.MetadataKey

In [72]:
mKey = openvds.core.MetadataKey(category='SurveyCoordinateSystem', name='CRSWkt', type=openvds.core.MetadataType.String)

In [73]:
mKey = openvds.core.MetadataKey(category='SurveyCoordinateSystem', name='Unit', type=openvds.core.MetadataType.String)
meta = layout.getMetadata(mKey)
print(meta)

m


In [74]:
mKey = openvds.core.MetadataKey(category='SurveyCoordinateSystem', name='Origin', type=openvds.core.MetadataType.DoubleVector2)
meta = layout.getMetadata(mKey)
print(meta)

(19.0, -32.0)


In [75]:
meta = layout.getMetadata(key_list[2])
print(meta)

(19.0, -32.0)


In [76]:
for v in key_list:
    print(v)
    meta = layout.getMetadata(v)
    print(meta)
    print()

MetadataKey(category='SurveyCoordinateSystem', name='CRSWkt', type=MetadataType.String)
utmXX

MetadataKey(category='SurveyCoordinateSystem', name='Unit', type=MetadataType.String)
m

MetadataKey(category='SurveyCoordinateSystem', name='Origin', type=MetadataType.DoubleVector2)
(19.0, -32.0)

MetadataKey(category='SurveyCoordinateSystem', name='InlineSpacing', type=MetadataType.DoubleVector2)
(3.0, 2.0)

MetadataKey(category='SurveyCoordinateSystem', name='CrosslineSpacing', type=MetadataType.DoubleVector2)
(-2.0, 3.0)

MetadataKey(category='SEGY', name='TextHeader', type=MetadataType.BLOB)
bytearray(b'\xc3@\xf1@\xc4\xc1\xe3\xc5@\xf2\xf0\xf2\xf3`\xf0\xf5`\xf1\xf6@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\xc3@\xf2@\xc1\xd5@\xc9\xd5\xc3\xd9\xc5\xc1\xe2\xc5@\xc9\xd5@\xc1\xd4\xd7\xd3\xc9\xe3\xe4\xc4\xc5@\xc5\xd8\xe4\xc1\xd3\xe2@\xc1\xd5@\xc9\xd5\xc3\xd9\xc5\xc1\xe2\xc5@\xc9\xd5@\xc1\xc3\xd6\xe4\xe2\xe3\xc9\xc3@\xc9\xd4\xd7\xc5\xc4\xc1\xd5\xc3\xc5@@@@@@@@@@@\xc3@\xf3@\xe6

In [77]:
layout.getMetadata('CrosslineSpacing')

TypeError: getMetadata(): incompatible function arguments. The following argument types are supported:
    1. (self: openvds.core.MetadataReadAccess, key: openvds.core.MetadataKey) -> PyMetadataVariant
    2. (self: openvds.core.MetadataReadAccess, category: str, name: str, type: openvds.core.MetadataType) -> PyMetadataVariant

Invoked with: <openvds.core.VolumeDataLayout object at 0x1050a4cf0>, 'CrosslineSpacing'

In [78]:
dir(layout)

['Dimensionality_Max',
 'VDSIJKGridDefinitionFromMetadata',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'channelCount',
 'contentsHash',
 'dimensionality',
 'getAxisDescriptor',
 'getChannelComponents',
 'getChannelCount',
 'getChannelDescriptor',
 'getChannelFormat',
 'getChannelIndex',
 'getChannelIntegerOffset',
 'getChannelIntegerScale',
 'getChannelMapping',
 'getChannelName',
 'getChannelNoValue',
 'getChannelUnit',
 'getChannelValueRangeMax',
 'getChannelValueRangeMin',
 'getContentsHash',
 'getDimensionMax',
 'getDimensionMin',
 'getDimensionName',
 'getDimensionNumSamples',
 'getDimensionUnit',
 'getDimensionality',
 'getLayoutDescriptor',
 'getLayoutHash',
 'getMetad